monedas = [1, 2, 5, 10, 20, 50, 100, 200]

suma = sum(monedas)
average = suma / len(monedas)
maximo = max(monedas)

print("El valor total de las monedas es: ", suma)
print("El promedio de las monedas es: ", average)
print("El valor maximo de todas las monedas es: ", maximo)

"""
Consigna:
Fácil: Los aventureros exploran un cofre del tesoro y encuentran una lista de
monedas de oro. Deben calcular la suma total de todas las monedas, el promedio de
su valor, y encontrar la moneda más valiosa.
"""