nom = input("Ingresa el nombre de tu personaje: ")
poison = input("Ingresa las posiones mágicas: ")

print("El nombre de tu personaje es: " + nom,"\n","El numero de tus posiones son: " + poison)

"""
Consigna:
Fácil: Pide al usuario que ingrese el nombre de su personaje y el número de
pociones mágicas que posee. Luego, muestra un mensaje que describe al personaje
y la cantidad de pociones que tiene.
"""