v = 100
d = 30

def time(d, v):
    return d / v
  
resultado = time(d, v)
print(resultado, "horas", "para la velocidad", v, "km/h", "a una distancia de", d, "km")

"""
Consigna:
Fácil: Los astronautas necesitan calcular el tiempo que les llevará llegar a la Luna.
Solicita al usuario que ingrese la distancia entre la Tierra y la Luna y la velocidad de
la nave espacial. Calcula y muestra el tiempo de viaje.
"""