obj = int(input("Ingrese el número del objeto(0 o 1): "))

if obj == 0:
  print("Acabas de encontrar un tesoro")
else:
  print("Solo encontraste un adorno")

"""
Consigna:
Intermedio: Mientras exploran la Ciudad Encantada, los jóvenes descubren un
mensaje enigmático tallado en una antigua estatua. Utiliza un programa que les
ayude a clasificar el mensaje como una pista útil para encontrar el tesoro o como
una distracción peligrosa.
"""