obj = int(input("Ingrese el número del objeto(0 o 1): "))

if obj == 0:
  print("Acabas de encontrar un tesoro")
else:
  print("Solo encontraste un adorno")

"""
Consigna:
Fácil: Los jóvenes encuentran un extraño artefacto en la Ciudad Encantada y deben
determinar si es un objeto valioso (tesoro oculto) o simplemente un adorno
decorativo. Escribe un programa que les ayude a tomar esta decisión.
"""